from __future__ import annotations


DIL_MODEL_DEFAULTS = {
    "hidden_size": 512,
    "intermediate_size": 1280,
    "num_encoder_layers": 6,
    "latent_size": 512,
    "max_word_bytes": 32,
    "context_radius": 2,
    "byte_conv_layers": 2,
    "byte_conv_kernel_size": 5,
    "byte_conv_expansion": 2,
    "dil_dropout": 0.10,
    "distillation_weight": 8.0,
    "mean_geometry_weight": 4.0,
    "variance_weight": 0.05,
    "writer_loss_weight": 1.0,
    "writer_num_layers": 6,
    "writer_conv_kernel_size": 5,
    "writer_conv_expansion": 4,
    "writer_dropout": 0.1,
    "writer_noise_warmup_steps": 1000,
    "writer_noise_clean_ratio": 0.10,
    "writer_noise_easy_ratio": 0.70,
    "writer_noise_mid_ratio": 0.20,
    "writer_noise_hard_ratio": 0.00,
    "writer_noise_easy_min_cos": 0.985,
    "writer_noise_easy_max_cos": 0.995,
    "writer_noise_mid_min_cos": 0.970,
    "writer_noise_mid_max_cos": 0.985,
    "writer_noise_hard_min_cos": 0.950,
    "writer_noise_hard_max_cos": 0.970,
}


DIL_TRAIN_DEFAULTS = {
    "data_mode": "streaming",
    "max_steps": 30000,
    "batch_size": 64,
    "eval_batch_size": 64,
    "nllb_batch_size": 64,
    "max_batch_reuse": 3,
    "text_read_chars": 4096,
    "prefetch_factor": 4,
    "learning_rate": 3e-4,
    "weight_decay": 0.1,
    "adam_beta1": 0.9,
    "adam_beta2": 0.95,
    "warmup_steps": 0,
    "max_grad_norm": 1.0,
    "log_every": 50,
    "checkpoint_every": 0,
    "eval_every": 0,
    "num_workers": 0,
    "seed": 1,
    "max_samples": 0,
}


NAZ_MODEL_DEFAULTS = {
    "hidden_size": 512,
    "intermediate_size": 2752,
    "num_hidden_layers": 12,
    "num_attention_heads": 8,
    "num_key_value_heads": 2,
    "head_dim": 64,
    "full_attention_interval": 4,
    "linear_key_head_dim": 64,
    "linear_value_head_dim": 64,
    "linear_num_key_heads": 8,
    "linear_num_value_heads": 8,
    "linear_conv_kernel_size": 4,
    "partial_rotary_factor": 0.25,
    "rope_theta": 10000000.0,
    "reconstruction_loss_weight": 1.0,
    "num_semantic_candidates": 4,
    "mtp_horizons": 3,
    "mtp_loss_weights": (1.0, 0.3, 0.15),
    "mixture_sigma": 1.1,
    "usage_balance_weight": 0.05,
    "router_responsibility_weight": 1.0,
    "moe_num_experts": 8,
    "moe_top_k": 2,
    "moe_layers": 4,
    "moe_balance_weight": 0.01,
    "naz_input_jitter_prob": 0.10,
    "naz_input_jitter_min_cos": 0.985,
    "naz_input_jitter_max_cos": 0.995,
    "repetition_cos_threshold": 0.985,
    "min_new_tokens": 1,
}


NAZ_TRAIN_DEFAULTS = {
    "data_mode": "cached",
    "max_steps": 30000,
    "batch_size": 8,
    "eval_batch_size": 8,
    "sequence_length": 128,
    "learning_rate": 3e-4,
    "weight_decay": 0.1,
    "adam_beta1": 0.9,
    "adam_beta2": 0.95,
    "warmup_steps": 0,
    "max_grad_norm": 1.0,
    "log_every": 50,
    "checkpoint_every": 0,
    "eval_every": 0,
    "max_eval_batches": 16,
    "text_read_chars": 1048576,
    "semantic_cache_chunk_tokens": 4096,
    "num_workers": 4,
    "prefetch_factor": 4,
    "seed": 1,
}


NAZ_FINETUNE_DEFAULTS = {
    "data_mode": "cached",
    "max_steps": 5000,
    "batch_size": 8,
    "eval_batch_size": 8,
    "sequence_length": 128,
    "learning_rate": 3e-5,
    "weight_decay": 0.05,
    "adam_beta1": 0.9,
    "adam_beta2": 0.95,
    "warmup_steps": 100,
    "max_grad_norm": 1.0,
    "log_every": 25,
    "checkpoint_every": 1000,
    "eval_every": 250,
    "max_eval_batches": 16,
    "text_read_chars": 1048576,
    "semantic_cache_chunk_tokens": 4096,
    "num_workers": 4,
    "prefetch_factor": 4,
    "seed": 1,
}
