from __future__ import annotations


DIL_MODEL_DEFAULTS = {
    "hidden_size": 512,
    "intermediate_size": 1280,
    "num_encoder_layers": 4,
    "num_decoder_layers": 4,
    "latent_size": 128,
    "max_word_bytes": 32,
    "context_left_radius": 2,
    "dil_dropout": 0.15,
    "kl_clamp": 0.5,
    "kl_weight": 1e-3,
    "ce_weight": 1.0,
    "distillation_weight": 8.0,
    "layer_geometry_weight": 2.0,
    "mean_geometry_weight": 4.0,
    "variance_weight": 0.05,
    "length_loss_weight": 0.5,
}


DIL_TRAIN_DEFAULTS = {
    "data_mode": "streaming",
    "max_steps": 30000,
    "batch_size": 64,
    "eval_batch_size": 64,
    "nllb_batch_size": 32,
    "max_batch_reuse": 2,
    "text_read_chars": 4096,
    "prefetch_factor": 4,
    "learning_rate": 3e-4,
    "weight_decay": 0.1,
    "adam_beta1": 0.9,
    "adam_beta2": 0.95,
    "warmup_steps": 0,
    "max_grad_norm": 1.0,
    "log_every": 50,
    "checkpoint_every": 0,
    "eval_every": 0,
    "num_workers": 0,
    "seed": 1,
    "max_samples": 0,
}


NAZ_MODEL_DEFAULTS = {
    "hidden_size": 512,
    "intermediate_size": 2752,
    "num_hidden_layers": 12,
    "num_attention_heads": 8,
    "num_key_value_heads": 2,
    "head_dim": 64,
    "full_attention_interval": 4,
    "linear_key_head_dim": 64,
    "linear_value_head_dim": 64,
    "linear_num_key_heads": 8,
    "linear_num_value_heads": 8,
    "linear_conv_kernel_size": 4,
    "partial_rotary_factor": 0.25,
    "rope_theta": 10000000.0,
    "num_mlp_layers": 4,
    "num_samples": 8,
    "energy_target_samples": 100,
    "pred_log_std_min": -4.0,
    "pred_log_std_max": 2.0,
    "log_std_loss_weight": 0.05,
    "decode_chunk_size": 32,
    "semantic_feedback": "mean",
    "beta": 1.0,
}


NAZ_TRAIN_DEFAULTS = {
    "data_mode": "streaming",
    "max_steps": 30000,
    "batch_size": 8,
    "eval_batch_size": 8,
    "sequence_length": 128,
    "learning_rate": 3e-4,
    "weight_decay": 0.1,
    "adam_beta1": 0.9,
    "adam_beta2": 0.95,
    "warmup_steps": 0,
    "max_grad_norm": 1.0,
    "log_every": 50,
    "checkpoint_every": 0,
    "eval_every": 0,
    "max_eval_batches": 16,
    "text_read_chars": 1048576,
    "num_workers": 4,
    "prefetch_factor": 4,
    "seed": 1,
}
